# Create a GitHub action to email a report from a file at 6 a.m. daily
name: email-report
on:
  schedule:
    - cron: "0 6 * * *"
jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: "Daily Report"
          body: "Please find attached the daily report."
          to: ${{ secrets.EMAIL }}
          attachments: "report.txt"